/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c008bbb1-dc72-4e6b-9920-a02d9748e588",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_HSCipjOUK",
    "aws_user_pools_web_client_id": "3uoagt4mj4ss6lfd9n6kvrm9dk",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ksu4ifkgnrawdjcz7x52i2u7hi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-r3g7ttvvwjh47k5gpp4xptupl4",
    "aws_user_files_s3_bucket": "dentalimages161006-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
